// Code generated by hertz generator.

package example

import (
	"context"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	example "github.com/xueyyyyyyu/hello-hertz/biz/model/hello/example"
)

var id2Name = map[int]string{}
var id2Favourite = map[int]string{}

// QueryMethod .
// @router /query [GET]
func QueryMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.QueryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(example.QueryResp)

	resp.Resp = "id: " + strconv.Itoa(int(req.ID)) + ", name: " + id2Name[int(req.ID)] +
		", favourite: " + id2Favourite[int(req.ID)]

	c.JSON(consts.StatusOK, resp)
}

// WriteMethod .
// @router /add-student-info [POST]
func WriteMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.AddStudentInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	id2Name[int(req.ID)] = req.Name
	id2Favourite[int(req.ID)] = req.Favourite

	resp := new(example.AddStudentInfoResp)

	c.JSON(consts.StatusOK, resp)
}
